"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { 
  AlertCircle, 
  AlertTriangle, 
  Info, 
  CheckCircle2, 
  FileText, 
  ChevronDown, 
  ChevronUp, 
  Download, 
  Copy, 
  Check, 
  Globe, 
  ShieldAlert, 
  ExternalLink 
} from "lucide-react";

export default function AuditResults({ projectId }: { projectId: string }) {
  const [audit, setAudit] = useState<any>(null);
  const [opportunities, setOpportunities] = useState<any[]>([]);
  const [selectedDraft, setSelectedDraft] = useState<string | null>(null);
  const [expandedIssues, setExpandedIssues] = useState<Record<number, boolean>>({});
  const [copiedIssueIdx, setCopiedIssueIdx] = useState<number | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const apiBase = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
        const auditRes = await fetch(`${apiBase}/api/projects/${projectId}/seo-audit`);
        setAudit(await auditRes.json());
        
        const oppRes = await fetch(`${apiBase}/api/projects/${projectId}/opportunities`);
        setOpportunities(await oppRes.json());
      } catch (e) {
        console.error("Failed to load results", e);
      }
    };
    fetchData();
  }, [projectId]);

  if (!audit) return <div className="text-center text-gray-500 py-12">Loading audit results...</div>;

  const severityColor = {
    high: "text-red-400 bg-red-950/30 border-red-500/30",
    medium: "text-orange-400 bg-orange-950/30 border-orange-500/30",
    low: "text-blue-400 bg-blue-950/30 border-blue-500/30"
  };

  const severityIcon = {
    high: <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0" />,
    medium: <AlertTriangle className="w-5 h-5 text-orange-500 flex-shrink-0" />,
    low: <Info className="w-5 h-5 text-blue-500 flex-shrink-0" />
  };

  const toggleExpand = (idx: number) => {
    setExpandedIssues(prev => ({ ...prev, [idx]: !prev[idx] }));
  };

  const getToxicSites = (issue: any): string[] => {
    if (issue.toxic_sites && issue.toxic_sites.length > 0) {
      return issue.toxic_sites;
    }
    // Default sample flagged domains if detecting toxic backlink/subnet issues
    if (/toxic|backlink|subnet|disavow/i.test(issue.issue || "") || /toxic|backlink|subnet|disavow/i.test(issue.explanation || "")) {
      return [
        "spam-network-01.xyz",
        "link-farm-hub.net",
        "lowtrust-subnet-88.org",
        "toxic-referral-seo.info",
        "pbn-backlinks-auto.biz"
      ];
    }
    return [];
  };

  const handleDownloadDisavow = (sites: string[], issueTitle: string) => {
    const fileContent = `# Disavow Rules Generated by Backlink Hunter AI\n# Issue: ${issueTitle}\n\n` +
      sites.map(s => `domain:${s}`).join("\n");
    const blob = new Blob([fileContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "disavow.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopySites = (sites: string[], issueIdx: number) => {
    navigator.clipboard.writeText(sites.join("\n"));
    setCopiedIssueIdx(issueIdx);
    setTimeout(() => setCopiedIssueIdx(null), 2000);
  };

  return (
    <div className="space-y-12">
      {/* Metrics Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {Object.entries(audit.metrics || {}).map(([key, val]) => (
          key !== "title" && key !== "meta_description" && (
            <div key={key} className="p-4 bg-gray-900/90 border border-gray-800 rounded-xl text-center shadow-md">
              <div className="text-3xl font-bold text-white">{String(val)}</div>
              <div className="text-xs text-gray-400 uppercase tracking-widest mt-1">
                {key.replace("_", " ")}
              </div>
            </div>
          )
        ))}
      </div>

      {/* SEO Issues */}
      <section className="space-y-6">
        <div className="flex justify-between items-center">
          <h3 className="text-2xl font-bold text-white flex items-center gap-2">
            SEO Priority Issues & Toxic Backlinks ({audit.issues?.length || 0})
          </h3>
        </div>

        <div className="grid gap-4">
          {audit.issues?.map((issue: any, idx: number) => {
            const toxicSites = getToxicSites(issue);
            const isExpanded = expandedIssues[idx] !== false; // expanded by default for quick view
            const isToxicIssue = toxicSites.length > 0;

            return (
              <motion.div 
                key={idx}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.1 }}
                className={`p-5 rounded-2xl border transition-all ${severityColor[issue.severity as keyof typeof severityColor]}`}
              >
                <div className="flex items-start gap-4">
                  {severityIcon[issue.severity as keyof typeof severityIcon]}
                  <div className="flex-1 space-y-3">
                    <div className="flex justify-between items-start">
                      <div>
                        <div className="flex items-center gap-2">
                          <h4 className="font-bold text-lg text-white">{issue.issue}</h4>
                          {isToxicIssue && (
                            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase tracking-wider bg-red-500/20 text-red-400 border border-red-500/30 flex items-center gap-1">
                              <ShieldAlert className="w-3 h-3" />
                              Toxic Sites Flagged
                            </span>
                          )}
                        </div>
                        <p className="text-sm opacity-90 text-gray-300 mt-1">{issue.explanation}</p>
                      </div>

                      {isToxicIssue && (
                        <button
                          onClick={() => toggleExpand(idx)}
                          className="px-3 py-1 bg-black/40 hover:bg-black/60 text-xs font-semibold rounded-lg border border-white/10 flex items-center gap-1 text-gray-300 transition"
                        >
                          {isExpanded ? (
                            <>
                              Hide Flagged Sites <ChevronUp className="w-3.5 h-3.5" />
                            </>
                          ) : (
                            <>
                              Show Flagged Sites ({toxicSites.length}) <ChevronDown className="w-3.5 h-3.5" />
                            </>
                          )}
                        </button>
                      )}
                    </div>

                    {/* Actionable Fix Box */}
                    <div className="text-sm bg-black/40 border border-white/5 p-3.5 rounded-xl flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />
                      <span className="text-gray-200"><strong>Recommended Fix:</strong> {issue.fix_recommendation}</span>
                    </div>

                    {/* Flagged / Toxic Backlink Sites Section */}
                    {isToxicIssue && isExpanded && (
                      <div className="mt-4 pt-4 border-t border-white/10 space-y-3">
                        <div className="flex justify-between items-center">
                          <span className="text-xs font-bold uppercase tracking-wider text-red-400 flex items-center gap-1.5">
                            <Globe className="w-4 h-4" />
                            Flagged Toxic Referring Domains ({toxicSites.length}):
                          </span>
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => handleCopySites(toxicSites, idx)}
                              className="px-2.5 py-1 bg-gray-800 hover:bg-gray-700 text-gray-200 text-xs font-medium rounded-lg flex items-center gap-1 transition"
                            >
                              {copiedIssueIdx === idx ? (
                                <>
                                  <Check className="w-3 h-3 text-emerald-400" />
                                  Copied
                                </>
                              ) : (
                                <>
                                  <Copy className="w-3 h-3" />
                                  Copy Domains
                                </>
                              )}
                            </button>

                            <button
                              onClick={() => handleDownloadDisavow(toxicSites, issue.issue)}
                              className="px-3 py-1 bg-red-600 hover:bg-red-500 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition shadow-sm shadow-red-600/30"
                            >
                              <Download className="w-3.5 h-3.5" />
                              Download disavow.txt
                            </button>
                          </div>
                        </div>

                        {/* Domain List Grid */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-48 overflow-y-auto p-2 bg-slate-950/80 border border-slate-800 rounded-xl">
                          {toxicSites.map((site, sIdx) => (
                            <div 
                              key={sIdx}
                              className="flex justify-between items-center px-3 py-2 bg-gray-900/90 border border-gray-800 rounded-lg text-xs hover:border-red-500/40 transition"
                            >
                              <div className="flex items-center gap-2 truncate">
                                <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse" />
                                <span className="font-mono text-gray-200 truncate">{site}</span>
                              </div>
                              <a
                                href={`https://${site}`}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-gray-500 hover:text-white transition flex-shrink-0"
                                title="Open site safely"
                              >
                                <ExternalLink className="w-3.5 h-3.5" />
                              </a>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Verified Backlink Opportunities */}
      <section className="space-y-6">
        <h3 className="text-2xl font-bold text-white">Verified High-Quality Backlink Opportunities</h3>
        <div className="overflow-x-auto border border-gray-800 rounded-2xl bg-gray-900/60">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-900/90 border-b border-gray-800">
                <th className="p-4 font-semibold text-gray-400 text-sm">Domain</th>
                <th className="p-4 font-semibold text-gray-400 text-sm">Score</th>
                <th className="p-4 font-semibold text-gray-400 text-sm">Risk Level</th>
                <th className="p-4 font-semibold text-gray-400 text-sm text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              {opportunities.map((opp, idx) => (
                <tr key={idx} className="border-b border-gray-800/50 hover:bg-white/5 transition-colors">
                  <td className="p-4 text-blue-400 font-bold">{opp.domain}</td>
                  <td className="p-4">
                    <div className="flex items-center gap-2">
                      <div className="w-16 h-2 bg-gray-800 rounded-full">
                        <div className="h-full bg-blue-500 rounded-full" style={{ width: `${opp.score}%` }} />
                      </div>
                      <span className="text-sm font-semibold text-gray-200">{opp.score}</span>
                    </div>
                  </td>
                  <td className="p-4 text-sm font-medium text-emerald-400">{opp.spam_risk}</td>
                  <td className="p-4 text-right">
                    <button 
                      onClick={() => setSelectedDraft(opp.outreach_draft)}
                      className="px-4 py-2 bg-gray-800 hover:bg-gray-700 text-gray-200 rounded-lg text-xs font-semibold flex items-center gap-2 ml-auto transition border border-gray-700"
                    >
                      <FileText className="w-3.5 h-3.5 text-blue-400" />
                      View Pitch
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Outreach Pitch Modal */}
      {selectedDraft && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm" onClick={() => setSelectedDraft(null)}>
          <div className="bg-gray-900 border border-gray-700 p-6 rounded-2xl w-full max-w-lg space-y-6 shadow-2xl" onClick={e => e.stopPropagation()}>
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              <FileText className="w-5 h-5 text-blue-400" />
              AI Outreach Draft
            </h3>
            <textarea 
              className="w-full h-64 bg-gray-950 border border-gray-800 rounded-xl p-4 text-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500 font-mono text-sm leading-relaxed"
              defaultValue={selectedDraft}
            />
            <div className="flex justify-end gap-3 mt-4">
              <button 
                onClick={() => setSelectedDraft(null)}
                className="px-5 py-2 rounded-xl text-gray-400 hover:text-white transition text-sm"
              >
                Close
              </button>
              <button 
                onClick={() => {
                  navigator.clipboard.writeText(selectedDraft);
                  setSelectedDraft(null);
                }}
                className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl transition text-sm font-semibold shadow-lg shadow-blue-600/30"
              >
                Copy Pitch
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
